# Demonstration: Test Storage Spaces Direct by using synthetic workloads 
# In this demonstration, you'll learn how to test Storage Spaces Direct by using synthetic workloads. 
# Prerequisites 
# To complete this demonstration, you will need: 
# •	A lab VM. 
# •	The Storage Spaces Direct Hyperconverged scenario deployed into the lab VM, as described in S2D Hyperconverged (https://aka.ms/s2d-hyperconverged)  . 
# •	All of the VMs in the Storage Spaces Direct Hyperconverged scenario, which should be running. 
# Note: For more information regarding the prerequisites, refer to the lab setup instructions for this module. 
# Preparation steps :
# 1.	Switch to the lab VM, and then from Hyper-V Manager, connect via an enhanced console session connected to the WSLab-S2D1 VM. 
# 2.	When prompted to sign in, provide the CORP\LabAdmin username and LS1setup! password. 
# 3.	Within the WSLab-S2D1 VM console session, from the Command Prompt, run the following com¬mand to start a Windows PowerShell session: 
# 4.	Run the following command to disable CSV Cache: 
(Get-Cluster).BlockCacheSize = 0 
# 5.	Run the following command to install the VM Fleet tools and set up the directory structure for its deployment: 
c:\VMFleet\install-VMFleet.ps1 -source C:\VMFleet 
# 6.	Run the following command to copy DiskSpeed.exe from the DC VM: 
Copy-Item -Path '\\DC\D$\DiskSpd\Diskspd.exe' -Destination 'c:\ClusterStorage\Collect\Control\Tools\ Diskspd.exe' 
# 7.	Run the following command to create per-node internal VM switches and deploy the VM Fleet VMs from the master image: 
c:\VMFleet\create-VMFleet.ps1 -basevhd C:\ClusterStorage\Collect\FleetImage.vhdx -vms 1 -admin-pass LS1setup! -connectuser Corp\Administrator -connectpass LS1setup! -FixedVHD:$False 
# 8.	Run the following command to adjust the number of virtual CPUs and memory sizes of VM Fleet VMs: 
c:\VMFleet\set-VMFleet.ps1 -ProcessorCount 2 -MemoryStartupBytes 512MB -MemoryMinimumBytes 512MB -MemoryMaximumBytes 2GB 
# 9.	Run the following command to start VM Fleet VMs: 
c:\VMFleet\Start-VMFleet.ps1 
# 10.	Run the following command to run the VM Fleet synthetic workload test based on an automated performance sweep: 
c:\VMFleet\start-sweep.ps1 -b 4 -t 2 -o 40 -w 0 -d 300 
<# Note: The parameters match those used by Diskspd.exe, including: 
•	b: buffer size in kibibytes (KiB) 
•	t: thread count 
•	o: outstanding I/O counts 
•	w: write ratio 
•	p: pattern (random: r, sequential: s, sequential interlocked: si) 
•	warm: duration of pre-measurement warmup (in seconds) 
•	d: duration of measured interval (in seconds) 
•	cool: duration of post-measurement cooldown (in seconds) 
#>
# 11.	Run the following command to start VM Fleet VMs: 
c:\VMFleet\Start-VMFleet.ps1 
# 12.	Run the following command to display a text-console monitoring performance monitor tracking across a cluster: 
c:\VMFleet\watch-cluster.ps1 
# 13.	Review the results generated by the test. 
